### ISSUE TITLE
Support devptr arg for nvstrings.sublist

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/nvstrings#2]
https://nvstrings.readthedocs.io/en/latest/api.html#nvstrings.nvstrings.sublist

For joins, sorts, groupbys etc, cuDF performs "gather" operations, which amounts to looking up values from a list of indexes.

nvstrings.sublist can be used for that, but we should support writing the result as a device array.

**Comment by randerzander** [comment]
@kkraus14 @davidwendt

**Comment by davidwendt** [comment]
The next release of nvstrings should include a new parameter for specifying a device array as input for `sublist()`

**Comment by davidwendt** [comment]
Method updated to accept device memory pointer in 0.2.0
