### ISSUE TITLE
How to use GPU other than 0

### ISSUE THREAD

**Issue by olyaromanyuk** [NVIDIA/nvstrings#6]
I have multiple GPU's available. Can you please advise me how can I do computations on, for example, GPU 1 instead of GPU 0

**Comment by davidwendt** [comment]
The easiest way is to set the environment variable: `CUDA_VISIBLE_DEVICES`. Here is a short article explaining how it works: https://training.acceleware.com/blog/cudavisibledevices-masking-gpus
So in Linux you can do this:
```
export CUDA_VISIBLE_DEVICES=1
python myapp.py
```
Calls to nvstrings will now use GPU1 instead of GPU0.

**Comment by olyaromanyuk** [comment]
Is there any other way? I was hoping to use this to parallelize the computations on multiple gpus, like put chunks of data on each gpu and then process it in multiple threads, environment variables don't look like a good way to do it

**Comment by randerzander** [comment]
@olyaromanyuk another way is to use numba:
```
from numba import cuda
cuda.select_device(gpu_id)
```

**Comment by olyaromanyuk** [comment]
Thank you, this will work

**Comment by randerzander** [comment]
please let us know if you find otherwise
